# Stage 1: Build frontend (React + Vite)
FROM node:18 AS build
WORKDIR /app

# Clone your frontend repo
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/PrasanthKonjeti0/docker_f.git .
RUN npm install
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
